name: Admin Theme
type: LocalGov Drupal
description: Sets up a nice administrative theme and navigation.

install:
  - admin_toolbar
  - admin_toolbar_tools
  - gin
  - gin_login
  - gin_toolbar
  - help
config:
  import:
    admin_toolbar: '*'
    admin_toolbar_tools: '*'
    gin:
      - gin.settings
      - block.block.gin_breadcrumbs
      - block.block.gin_content
      - block.block.gin_help
      - block.block.gin_local_actions
      - block.block.gin_messages
      - block.block.gin_page_title
      - block.block.gin_primary_local_tasks
    gin_login: '*'
  actions:
    # Set and unset Gin blocks.
    block.block.gin_admin:
      simple_config_update:
        status: false
    block.block.gin_branding:
      simple_config_update:
        status: false
    block.block.gin_local_actions:
      simple_config_update:
        region: content
        weight: -10
    block.block.gin_local_tasks:
      simple_config_update:
        status: false
    block.block.gin_page_title:
      simple_config_update:
        region: header
        weight: -10
    block.block.gin_primary_local_tasks:
      simple_config_update:
        region: header
        weight: -5
        settings.secondary: true
    block.block.gin_tools:
      simple_config_update:
        status: false
    system.theme:
      simple_config_update:
        admin: gin
        classic_toolbar: horizontal
